baseURL = "https://raddads.netlify.app"
googleAnalytics = ""
theme = ""
title = "Rad Dads Landscape Design"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1
[[menu.main]]
name = "About"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "Products"
pre = "#"
url = "products"
weight = 3
[[menu.main]]
name = "Career"
pre = ""
url = "career"
weight = 4
[[menu.main]]
name = "Hit us Up"
pre = "#"
url = "contact"
weight = 5
[params]
author = "pop2"
contact_info = "Call or Text Us : 512-731-2397"
description = "Rad Dads Landscaping"
logo = "images/raddads.png"
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCLeL2OEUYtqk5ptyUYA5R5VDpOYi6Z9nQ"
map_center_lat = "30.266666"
map_center_lng = "-97.733330"
map_marker = "images/map-marker.png"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
[[params.social]]
icon = "fa-instagram"
link = "https://www.instagram.com/raddadslandscaping"
title = "instagram"
